# Generated by Django 2.1.3 on 2018-11-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagpuanApp', '0003_auto_20181117_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='landmark',
            field=models.CharField(max_length=50),
        ),
    ]
