# Generated by Django 2.1.3 on 2018-11-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagpuanApp', '0004_auto_20181117_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='Lost', max_length=50),
        ),
    ]
